binderhub-service:
  buildPodsRegistryCredentials:
    server: 
    username:  # Container registry credentials username
    password:  # Container registry credentials password                
  config:
    BinderHub:
      auth_enabled: false
      use_registry: true
      image_prefix: 
      base_url: /services/binder
