apiVersion: v1
data:
  postgresPassword: TG9od0x4a2RwSXYzZjF5SkJsUGxLS2MzdENHM2pHVmI=
  userPassword: TVBIeUhUTlFMWmpkYXdDN1BicUFWWGQ4QWd1M2d0NGM=
kind: Secret
metadata:
  name: postgres-credentials
  namespace: postgres
type: Opaque
