name: Build and Release Wrapper Chart

on:
  workflow_dispatch:

env:
  PINNED_VERSION: "3.2.3"
  WRAPPER_CHART_PATH: "eodc/jupyter-enterprise-gateway" 

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Embed Upstream Dependency
        run: |
          git clone --depth 1 --filter=blob:none --sparse https://github.com/jupyter-server/enterprise_gateway.git temp_upstream
          cd temp_upstream
          git sparse-checkout set etc/kubernetes/helm/enterprise-gateway
          tar -cf - -C etc/kubernetes/helm/enterprise-gateway . | tar -xf - -C ../${{ env.WRAPPER_CHART_PATH }}
          cd ..
          rm -rf temp_upstream

      - name: Pin Versions (Base & Wrapper)
        run: |
          WRAPPER_CHART="${{ env.WRAPPER_CHART_PATH }}/Chart.yaml"
          BASE_CHART="${{ env.WRAPPER_CHART_PATH }}/Chart.yaml"
          sed -i "s/^version: .*/version: ${{ env.PINNED_VERSION }}/" $BASE_CHART
          sed -i "s/^appVersion: .*/appVersion: ${{ env.PINNED_VERSION }}/" $BASE_CHART
          sed -i "s/^version: .*/version: ${{ env.PINNED_VERSION }}/" $WRAPPER_CHART
          sed -i "s/^appVersion: .*/appVersion: ${{ env.PINNED_VERSION }}/" $WRAPPER_CHART
          sed -i 's|repository: oci://.*|repository: "file://./charts/enterprise-gateway"|' $WRAPPER_CHART

      - name: Build and Package
        run: |
          helm package ${{ env.WRAPPER_CHART_PATH }} --destination .
          
          echo "Package created:"
          ls *.tgz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.PINNED_VERSION }}
          files: "*.tgz"
          generate_release_notes: true
