name: Release upstream JEG chart

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "jeg-*"
    paths:
      - eodc/jupyter-enterprise-gateway/**

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
  
    env:
      LOCAL_CHART: eodc/enterprise-gateway
      NEW_CHART: /tmp/jeg-chart-new
      UPSTREAM_REPO: jupyter-server/enterprise_gateway
      UPSTREAM_CHART_PATH: etc/kubernetes/helm/enterprise-gateway
      
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Get most recent JEG chart
        run: |
          git clone --depth 1 --filter=blob:none --sparse "https://github.com/${UPSTREAM_REPO}.git" /tmp/jeg-repo
          cd /tmp/jeg-repo
          git sparse-checkout set "${UPSTREAM_CHART_PATH}"
          mkdir --parent "${NEW_CHART}"
          rsync --archive "${UPSTREAM_CHART_PATH}/" "${NEW_CHART}"

      - name: Detect changes vs local chart
        id: diff
        shell: bash
        run: |
          mkdir --parent "${LOCAL_CHART}"
          if diff --brief --recursive "${LOCAL_CHART}" "${NEW_CHART}"/ >/dev/null 2>&1; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Update working tree with upstream chart
        if: steps.diff.outputs.changed == 'true'
        run: |
          rm --force --recursive "${LOCAL_CHART}"
          mkdir --parent "${LOCAL_CHART}"
          rsync --archive "${NEW_CHART}"/ "${LOCAL_CHART}/"
      
      - name: Helm lint
        if: steps.diff.outputs.changed == 'true'
        run: |
          helm lint "${LOCAL_CHART}"
          
      - name: Run chart-releaser
        if: steps.diff.outputs.changed == 'true'
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: eodc
          packages_with_index: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: No changes detected
        if: steps.diff.outputs.changed != 'true'
        run: echo "No changes in upstream Enterprise Gateway chart. Skipping release."
