name: Release JupyterHub Charts

on:
  push:
    branches:
      - main
    paths:
      - eodc/jupyterhub/**

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: add repos
        run: |
          helm repo add jupyterhub https://hub.jupyter.org/helm-chart/
          helm repo add binderhub-service https://2i2c.org/binderhub-service

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: eodc/jupyterhub
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"