apiVersion: v1
kind: Secret
metadata:
  name: "postgres-credentials"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Values.pygeoapi.secret.namespace .Values.pygeoapi.secret.name ) }}
  {{- $secretData := (get $secretObj "data") }}
  {{- $postgresspassword := (get $secretData .Values.pygeoapi.secret.key) }}
  postgresPassword: {{ $postgresspassword | quote }}
