apiVersion: v1
kind: Secret
metadata:
  name: "postgres-credentials"
type: Opaque
data:
  # generate a random password data
  postgresPassword: {{ default (randAlphaNum 32 | b64enc) }}
  userPassword: {{ default (randAlphaNum 32 | b64enc) }}